/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.XemChiTietLuongCaNhan;

import controller.QuanLyThongTinCaNhanController;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;
import util.IUpdateTableEvent;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import controller.BaoTriThongTinTaiKhoanController;
import java.io.IOException;
import view.DangNhap.DangNhapUI;
/**
 *
 * @author Admin
 */
public class XemChiTietLuongCaNhanUI extends javax.swing.JFrame {
    private HashMap<String, Object> data;
    QuanLyThongTinCaNhanController quanLyThongTinCaNhanController;
    BaoTriThongTinTaiKhoanController baoTriThongTinTaiKhoanController=new BaoTriThongTinTaiKhoanController();
    DangNhapUI dangNhapUI = new DangNhapUI();;
    public XemChiTietLuongCaNhanUI(HashMap<String, Object> data) throws SQLException, IOException {
        this.data = data;
        initComponents();
        generateComboBoxData();
        setLocationRelativeTo(null);
        quanLyThongTinCaNhanController = new QuanLyThongTinCaNhanController();
       
        UpdateTable("where mataikhoan=",dangNhapUI.getTenTK());

        quanLyThongTinCaNhanController.setUpdateTableEvent(new IUpdateTableEvent() {
            @Override
            public void onUpdateDataOnTableEvent() {
                try {
                    UpdateTable("where mataikhoan=",dangNhapUI.getTenTK());
                } catch (SQLException ex) {
                    Logger.getLogger(XemChiTietLuongCaNhanUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboThang = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cboNam = new javax.swing.JComboBox<>();
        btnXemLuongTheoThoiGian = new javax.swing.JButton();
        btnXemLuongTheoThoiGian1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Xem Chi Tiết Lương Cá Nhân");

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+11));
        jLabel1.setText("Xem Chi Tiết Lương Cá Nhân");

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getSize()+3f));
        jLabel2.setText("Tháng:");

        cboThang.setFont(cboThang.getFont().deriveFont(cboThang.getFont().getSize()+3f));

        jLabel3.setFont(jLabel3.getFont().deriveFont(jLabel3.getFont().getSize()+3f));
        jLabel3.setText("Năm:");

        cboNam.setFont(cboNam.getFont().deriveFont(cboNam.getFont().getSize()+3f));

        btnXemLuongTheoThoiGian.setFont(btnXemLuongTheoThoiGian.getFont().deriveFont(btnXemLuongTheoThoiGian.getFont().getSize()+3f));
        btnXemLuongTheoThoiGian.setText("Xem Lương Theo Thời Gian");
        btnXemLuongTheoThoiGian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemLuongTheoThoiGianActionPerformed(evt);
            }
        });

        btnXemLuongTheoThoiGian1.setFont(btnXemLuongTheoThoiGian1.getFont().deriveFont(btnXemLuongTheoThoiGian1.getFont().getSize()+3f));
        btnXemLuongTheoThoiGian1.setText("Toàn Bộ Lương Theo Thời Gian");
        btnXemLuongTheoThoiGian1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemLuongTheoThoiGian1ActionPerformed(evt);
            }
        });

        jTable1.setFont(jTable1.getFont().deriveFont(jTable1.getFont().getSize()+3f));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Công", "Tháng", "Năm", "Hệ Số Lương", "Tiền Phụ Cấp", "Tiền Thưởng", "Tổng Lương"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        back.setText("Quay lại");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnXemLuongTheoThoiGian)
                .addGap(18, 18, 18)
                .addComponent(btnXemLuongTheoThoiGian1)
                .addGap(185, 185, 185))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(back)))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(cboNam, 0, 377, Short.MAX_VALUE)
                            .addComponent(cboThang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(back))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXemLuongTheoThoiGian)
                    .addComponent(btnXemLuongTheoThoiGian1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        dispose();
        
    }//GEN-LAST:event_backActionPerformed

    private void btnXemLuongTheoThoiGianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemLuongTheoThoiGianActionPerformed
    
        try {
            String thang=(String) cboThang.getSelectedItem();
            String nam=(String) cboNam.getSelectedItem();
            UpdateTable("where thang= "+thang+" and nam="+nam+ " and mataikhoan=",dangNhapUI.getTenTK());
        } catch (SQLException ex) {
            Logger.getLogger(XemChiTietLuongCaNhanUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnXemLuongTheoThoiGianActionPerformed

    private void btnXemLuongTheoThoiGian1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemLuongTheoThoiGian1ActionPerformed
        try {
            // TODO add your handling code here:
            UpdateTable("where mataikhoan=",dangNhapUI.getTenTK());
        } catch (SQLException ex) {
            Logger.getLogger(XemChiTietLuongCaNhanUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnXemLuongTheoThoiGian1ActionPerformed
  
      public void UpdateTable(String queryString,String tenTK) throws SQLException { 
          long matk= baoTriThongTinTaiKhoanController.onFindTaiKhoanID(tenTK);
          
          ArrayList<String> dsluongcanhan = quanLyThongTinCaNhanController.onQueryAllUserCheckCaNhan(queryString+matk,true); 
          DefaultTableModel defaultTableModel = (DefaultTableModel) jTable1.getModel(); 
          
          while (defaultTableModel.getRowCount() > 0) {  
              defaultTableModel.removeRow(0);  
          } 
          for (int i = 0; i < dsluongcanhan.size(); i++) { 
              String[] strings = dsluongcanhan.get(i).split(","); 
              float luongCoBan = Float.parseFloat(strings[3]); 
              long soGioLamThem = Long.parseLong(strings[4]); 
              long soNgayNghi = Long.parseLong(strings[5]); 
              float tongluong; 
              tongluong = luongCoBan * (soGioLamThem + soNgayNghi);
              String[] datas = new String[strings.length + 1]; 
              System.arraycopy(strings, 0, datas, 0, strings.length); 
              datas[strings.length] = String.valueOf(tongluong);
              defaultTableModel.addRow((Object[]) datas); 
          } 
      }
      
    
    public void onStartGUI() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XemChiTietLuongCaNhanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XemChiTietLuongCaNhanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XemChiTietLuongCaNhanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XemChiTietLuongCaNhanUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new XemChiTietLuongCaNhanUI(data).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(XemChiTietLuongCaNhanUI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(XemChiTietLuongCaNhanUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    private void generateComboBoxData(){
        ArrayList<String> thang = new ArrayList(); 
        
        for(int i = 1 ; i <= 12 ; i++){
            thang.add(String.valueOf(i));
        }
      
        ArrayList<String> nam = new ArrayList<>();
        
        for (int i = 1970; i <= 2022; i++) {
            nam.add(String.valueOf(i));
        }
        
       cboThang.setModel(new DefaultComboBoxModel<>(thang.toArray(new String[thang.size()])));
       cboThang.setSelectedIndex(0);
       cboNam.setModel(new DefaultComboBoxModel<>(nam.toArray(new String[nam.size()])));
       cboNam.setSelectedIndex(0);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton btnXemLuongTheoThoiGian;
    private javax.swing.JButton btnXemLuongTheoThoiGian1;
    private javax.swing.JComboBox<String> cboNam;
    private javax.swing.JComboBox<String> cboThang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
