/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.DangKy;

import controller.DangKyController;
import model.TaiKhoan;
import view.BaoTriThongTinChamCong.BaoTriThongTinChamCongUI;
import view.BaoTriThongTinTaiKhoan.BaoTriThongTinTaiKhoanUI;
import view.DangNhap.DangNhapUI;
import view.TuyChonUI;
import util.IOptionEvent;
import java.util.HashMap;
import javax.swing.JOptionPane;
import util.ISendDataToAnotherGUI;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Admin
 */
public class TaoTaiKhoanBoiAdminUI extends javax.swing.JFrame {

    private static ISendDataToAnotherGUI putDataInterface;

    /**
     * Creates new form TaoTaiKhoanBoiAdminUI1
     */
    private HashMap<String, Object> data;
    public TaoTaiKhoanBoiAdminUI(HashMap<String, Object> data) {
        this.data = data;
        initComponents();
        setLocationRelativeTo(null);
    }

    public void setPutDataInterface(ISendDataToAnotherGUI putDataInterface) {
        this.putDataInterface = putDataInterface;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTaoTaiKhoan = new javax.swing.JButton();
        btnResetThongTin = new javax.swing.JButton();
        txtTaiKhoan = new javax.swing.JTextField();
        cboQuyen = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnQuayLai = new javax.swing.JButton();
        txtMatKhau = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTaoTaiKhoan.setFont(btnTaoTaiKhoan.getFont().deriveFont(btnTaoTaiKhoan.getFont().getSize()+3f));
        btnTaoTaiKhoan.setText("Tạo Tài Khoản Mới");
        btnTaoTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoTaiKhoanActionPerformed(evt);
            }
        });

        btnResetThongTin.setFont(btnResetThongTin.getFont().deriveFont(btnResetThongTin.getFont().getSize()+3f));
        btnResetThongTin.setText("Reset Thông Tin");
        btnResetThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetThongTinActionPerformed(evt);
            }
        });

        txtTaiKhoan.setFont(txtTaiKhoan.getFont().deriveFont(txtTaiKhoan.getFont().getSize()+3f));

        cboQuyen.setFont(cboQuyen.getFont().deriveFont(cboQuyen.getFont().getSize()+3f));
        cboQuyen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản Trị Viên", "Giảng Viên", "Kế Toán", "Nhân Sự", "Giám Đốc" }));

        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+11));
        jLabel1.setText("Lập Tài Khoản Mới");

        jLabel6.setFont(jLabel6.getFont().deriveFont(jLabel6.getFont().getSize()+3f));
        jLabel6.setText("Tài Khoản");

        jLabel7.setFont(jLabel7.getFont().deriveFont(jLabel7.getFont().getSize()+3f));
        jLabel7.setText("Mật Khẩu");

        jLabel8.setFont(jLabel8.getFont().deriveFont(jLabel8.getFont().getSize()+3f));
        jLabel8.setText("Quyền");

        btnQuayLai.setText("Quay Lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        txtMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnQuayLai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(190, 190, 190))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTaoTaiKhoan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnResetThongTin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTaiKhoan)
                            .addComponent(cboQuyen, 0, 300, Short.MAX_VALUE)
                            .addComponent(txtMatKhau))))
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnQuayLai))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTaoTaiKhoan)
                    .addComponent(btnResetThongTin))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetThongTinActionPerformed
        txtTaiKhoan.setText("");
        txtMatKhau.setText("");
        cboQuyen.setSelectedIndex(0);
    }//GEN-LAST:event_btnResetThongTinActionPerformed

    private void btnTaoTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoTaiKhoanActionPerformed
//        try {
//            String taiKhoan = txtTaiKhoan.getText();
//            String matKhau = txtMatKhau.getText();
//            int quyen = cboQuyen.getSelectedIndex();
//
//            taiKhoan = taiKhoan.trim();
//            matKhau = matKhau.trim();
//            if("".equals(taiKhoan) || "".equals(matKhau)){
//                throw new Exception("Không được để trống Tài Khoản/Mật khẩu");
//            }
//            
//            if(putDataInterface != null){
//                var myHashMap = new HashMap<String, Object>();
//                myHashMap.put("TaiKhoan", taiKhoan);
//                myHashMap.put("Quyen", quyen);
//                putDataInterface.onGetData(myHashMap);
//            }else{
//                throw new Exception("Chưa thể đẩy data sang");
//            }            
//            JOptionPane.showMessageDialog(this.getContentPane(), DangKyController.onRegisterEvent(new TaiKhoan(taiKhoan, matKhau, quyen)), "Thông Báo", JOptionPane.OK_OPTION);
//            dispose();
//        } catch (Exception ex) {
//            JOptionPane.showMessageDialog(this.getContentPane(), ex.getMessage(), "Thông Báo", JOptionPane.OK_OPTION);
//            ex.printStackTrace();
//
//        }
        try {
            String taiKhoan = txtTaiKhoan.getText();
            String matKhau = String.valueOf(txtMatKhau.getPassword());
            int quyen = 0;
            switch(cboQuyen.getSelectedItem().toString()) {
                case "Quản trị viên" -> {
                    quyen = 0;
                }
                
                case "Giảng viên" -> {
                    quyen = 1;
                }
                
                case "Giám đốc" -> {
                    quyen = 4;
                }
                
                case "Kế toán" -> {
                    quyen = 2;
                }
                
                case "Nhân sự" -> {
                    quyen = 3;
                }
            }

            taiKhoan = taiKhoan.trim();
            matKhau = matKhau.trim();
            if ("".equals(taiKhoan) || "".equals(matKhau)) {
                throw new Exception("Không được để trống mật khẩu");
            } else {
                String thongbao = DangKyController.onRegisterEvent(new TaiKhoan(taiKhoan, matKhau, quyen));
                JOptionPane.showMessageDialog(this.getContentPane(), thongbao, "Thông Báo", JOptionPane.OK_OPTION);
                if (thongbao.equals("Tạo Tài Khoản Thành Công")) {
                    new BaoTriThongTinTaiKhoanUI(data).onStartGUI();
                    dispose();
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this.getContentPane(), ex.getMessage(), "Thông Báo", JOptionPane.OK_OPTION);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnTaoTaiKhoanActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        try {
            new BaoTriThongTinTaiKhoanUI(data).onStartGUI();
        } catch (SQLException ex) {
            Logger.getLogger(TaoTaiKhoanBoiAdminUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public void onStartGUI() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaoTaiKhoanBoiAdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaoTaiKhoanBoiAdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaoTaiKhoanBoiAdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaoTaiKhoanBoiAdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaoTaiKhoanBoiAdminUI(data).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnResetThongTin;
    private javax.swing.JButton btnTaoTaiKhoan;
    private javax.swing.JComboBox<String> cboQuyen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField txtMatKhau;
    public javax.swing.JTextField txtTaiKhoan;
    // End of variables declaration//GEN-END:variables

    public void setPutDataInterface() {
    }
}
