/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DepartmentForm;

import Database.DBEngine;
import EmployeeForm.EmployeeDTO;
import static java.awt.image.ImageObserver.WIDTH;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author admin
 */
public class Department extends javax.swing.JFrame {
    
    ArrayList<DepartmentDTO> list = new ArrayList<DepartmentDTO>();
    ArrayList<DepartmentDTO> listDp = new ArrayList<DepartmentDTO>();
    ArrayList<EmployeeDTO> list_E = new ArrayList<EmployeeDTO>();
    Map<String,Integer> noe = new HashMap<>();
    /**
     * Creates new form Manager
     */
    private int rows = -1;
    
    DepartmentDTO dp = new DepartmentDTO();
    static String NameFile = "src\\Database\\Department.txt";
    static String NameFileE = "src\\Database\\Employee.txt";
    static DBEngine db = new DBEngine();
    
    public Department() {
        initComponents();
        setLocationRelativeTo(null);
        
    }
    
    public void DisplayList(){
        getData();
        list.addAll(listDp);
        loadTable();
    }
    
    public void ReadFileEmployee(){
        try {
           list_E = (ArrayList<EmployeeDTO>) db.ReadFile(NameFileE);
           for(DepartmentDTO ndp:list){
            noe.put(ndp.getName(), 0);
        }
        for(EmployeeDTO ne : list_E){
            noe.put(ne.getDepartment(), noe.get(ne.getDepartment()) + 1);
        }
        for(DepartmentDTO ndp:list){
            ndp.setNumber(noe.get(ndp.getName()));
        }
        for(DepartmentDTO ndp:list){
            ndp.setQuantity(ndp.getNumber()+"");
        }
        SaveData();
        loadTable();
        } catch (Exception e) {
            System.out.println(e);
        }
        
        
    }
    
    public boolean isValidDateFormat(String input) {
        String regex = "\\d{2}/\\d{2}/\\d{4}";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(input);
        return matcher.matches();
    }
    
    public boolean CheckIDandName(DepartmentDTO newDp){
        for (DepartmentDTO dpp : list) {
            if (dpp.getID().equals(newDp.getID()) || dpp.getName().equals(newDp.getName())){
                return false;
            }
        }
            
        return true;
    }
    
    public boolean Check(DepartmentDTO newDp,int rows){
        int cnt = 0;
        
        for (DepartmentDTO dpp : list) {
            if(cnt == rows){
            cnt++;
            continue;
        }
            if (dpp.getID().equals(newDp.getID()) || dpp.getName().equals(newDp.getName())){
                return false;
            }
            cnt++;
        }
            
        return true;
    }
    
    public boolean CheckNumber(String number){
        try {
            Integer.valueOf(number);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    
    public void SaveData(){
        try {
            db.SaveFile(NameFile, list);
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    public void getData(){
        try {
           listDp = (ArrayList<DepartmentDTO>) db.ReadFile(NameFile);
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void loadTable(){
//        for(Employee ndp:list_E){
//            System.out.println(ndp.toString());
//        }
        tblDepartment.setModel(new DepartmentDAO(list));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtManager = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnFix = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        cbDepartment = new javax.swing.JComboBox<>();
        btnFilter = new javax.swing.JButton();
        ListDepartment = new javax.swing.JScrollPane();
        tblDepartment = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btnDivision = new javax.swing.JCheckBox();
        btnFaculty = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("ID");

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Manager");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Date");

        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnFix.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnFix.setText("Fix");
        btnFix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFixActionPerformed(evt);
            }
        });

        btnRemove.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        cbDepartment.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cbDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Division", "Faculty" }));
        cbDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDepartmentActionPerformed(evt);
            }
        });

        btnFilter.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnFilter.setText("Filter by department");
        btnFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilterActionPerformed(evt);
            }
        });

        tblDepartment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblDepartment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDepartmentMouseClicked(evt);
            }
        });
        ListDepartment.setViewportView(tblDepartment);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Type");

        btnGroup.add(btnDivision);
        btnDivision.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnDivision.setText("Division");
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionActionPerformed(evt);
            }
        });

        btnGroup.add(btnFaculty);
        btnFaculty.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnFaculty.setText("Faculty");
        btnFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacultyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(41, 41, 41)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnFix, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtManager, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnRemove)))
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(ListDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(cbDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFilter)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(btnDivision)
                    .addComponent(btnFaculty))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnFix)
                    .addComponent(btnRemove))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFilter))
                .addGap(18, 18, 18)
                .addComponent(ListDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
         // TODO add your handling code here:
        if("".equals(txtID.getText()) || "".equals(txtName.getText()) || "".equals(txtManager.getText()) || "".equals(txtDate.getText()) || (!btnDivision.isSelected() && !btnFaculty.isSelected())){
             JOptionPane.showConfirmDialog(this,"Not enough information !!","Notification", WIDTH);
        }
        else{
        DepartmentDTO newDp = new DepartmentDTO();
        newDp.setID(txtID.getText());
        newDp.setName(txtName.getText());
        if(btnDivision.isSelected()){
            newDp.setType("Division");
        }else{
            newDp.setType("Faculty");
        }
        newDp.setManager(txtManager.getText());
        newDp.setQuantity(newDp.getNumber() + "");
        newDp.setDate(txtDate.getText());
            if(!CheckIDandName(newDp)){
                JOptionPane.showConfirmDialog(this,"Duplicate ID and Name information !!","Notification", WIDTH);
            }
            else if(!isValidDateFormat(newDp.getDate())){
                JOptionPane.showConfirmDialog(this,"Incorrect date format entered !!","Notification", WIDTH);
            }
            else{
                list.add(newDp);
                SaveData();
                loadTable();       
                txtID.setText("");
                txtName.setText("");
                btnGroup.clearSelection();
                txtManager.setText("");
                txtDate.setText("");
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed
                
    
    private void btnFixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFixActionPerformed
        // TODO add your handling code here:
        rows = tblDepartment.getSelectedRow();
        if(rows !=-1){
        DepartmentDTO newDp = new DepartmentDTO();
        newDp.setID(txtID.getText());
        newDp.setName(txtName.getText());
        if(btnDivision.isSelected()){
            newDp.setType("Division");
        }else{
            newDp.setType("Faculty");
        }
        newDp.setManager(txtManager.getText());
        newDp.setQuantity(newDp.getNumber() + "");
        newDp.setDate(txtDate.getText());
            if(!isValidDateFormat(newDp.getDate())){
                JOptionPane.showConfirmDialog(this,"Incorrect date format entered !!","Notification", WIDTH);
            }
            else if(!Check(newDp,rows)){
                JOptionPane.showConfirmDialog(this,"Duplicate ID and Name information !!","Notification", WIDTH);
            }
            else{
                list.set(rows,newDp);
                SaveData();
                loadTable();
                txtID.setText("");
                txtName.setText("");
                txtManager.setText("");
                txtDate.setText("");
            }
        
        }else{
            JOptionPane.showConfirmDialog(this,"No line selected!","Notification", HEIGHT);
        }
        
    }//GEN-LAST:event_btnFixActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        rows = tblDepartment.getSelectedRow();
        if(rows != -1){
            list.remove(rows);
            SaveData();
            loadTable();
        }
        else{
             JOptionPane.showConfirmDialog(this,"No line selected!","Notification", HEIGHT);
        }
        txtID.setText("");
        txtName.setText("");
        btnGroup.clearSelection();
        txtManager.setText("");
        txtDate.setText("");
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilterActionPerformed
        // TODO add your handling code here:]
       ArrayList<DepartmentDTO> data = new ArrayList<>();
       list.clear();
       for(DepartmentDTO newDp:listDp){
           data.add(newDp);
       }
       String nameType = (String)cbDepartment.getSelectedItem();
       if(nameType.equals("All")){           
           list.addAll(data);
       }else{
           for(DepartmentDTO newDp:data){
               if(newDp.getType().equals(nameType)){
                   list.add(newDp);
               }
           }
       }
       loadTable();
    }//GEN-LAST:event_btnFilterActionPerformed

    private void cbDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDepartmentActionPerformed

    private void tblDepartmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDepartmentMouseClicked
        // TODO add your handling code here:
        rows = tblDepartment.getSelectedRow();
        if(rows != -1){
        dp = list.get(rows);
        txtID.setText(dp.getID());
        txtName.setText(dp.getName());
        boolean isSelected = ("Division".equals(dp.getType()));
        btnDivision.setSelected(isSelected);
        btnFaculty.setSelected(!isSelected);
        txtManager.setText(dp.getManager());
        txtDate.setText(dp.getDate());
        }
    }//GEN-LAST:event_tblDepartmentMouseClicked

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_btnDivisionActionPerformed

    private void btnFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacultyActionPerformed
        // TODO add your handling code here:
        btnFaculty.setSelected(false);
    }//GEN-LAST:event_btnFacultyActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        DisplayList();
        ReadFileEmployee();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Department().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ListDepartment;
    private javax.swing.JButton btnAdd;
    private javax.swing.JCheckBox btnDivision;
    private javax.swing.JCheckBox btnFaculty;
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnFix;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton btnRemove;
    private javax.swing.JComboBox<String> cbDepartment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTable tblDepartment;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtManager;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    private boolean isStringDigits(String valueOf) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
